node:
  - name: node01
    ip: 10.203.1.238
    bond_ip: None
    username: root
    password: password
    disk_path: /dev/sda2
  - name: node02
    ip: 10.203.1.111
    bond_ip: None
    username: root
    password: password
    disk_path: /dev/sda2
  - name: node03
    ip: 10.203.1.240
    bond_ip: None
    username: root
    password: 8500960
    disk_path: /dev/sda2