resource_definition: test01
resource_size: 1G
node:
  - name: master2204
    ip: 192.168.16.128
    bond_ip:
    username: root
    password: password
    disk_path: /dev/sdb
    network_card:
    vgname:
  - name: node12204
    ip: 192.168.16.130
    bond_ip:
    username: root
    password: password
    disk_path: /dev/sdb
    network_card:
    vgname:
  - name: node22204
    ip: 192.168.16.129
    bond_ip: 
    username: root
    password: password
    disk_path: /dev/sdb
    network_card:
    vgname: