node:
  - name:
    ip:
    bond_ip:
    username:
    password:
    disk:
  - name:
    ip:
    bond_ip:
    username:
    password:
    disk:
  - name:
    ip:
    bond_ip:
    username:
    password:
    disk: