node:
  - name:   #做diskless
    ip:
    bond_ip:
    username:
    password:
    disk_path:
    nic:
  - name:   #做diskful
    ip:
    bond_ip:
    username:
    password:
    nic:
  - name:   #做diskful
    ip:
    bond_ip: 
    username:
    password:
    nic:
phynode:
  - ip:
    username:
    password:
Cycle execution times: 1